Criação do Autor é dos métodos de validação e retorno de um autor
larissafabiao/nossa-casa-codigo pull request #3
Opened 2020-06-03 21:30 UTC by larissafabiao

Nesta Branch optei por mudar minha estrutura de armazenamento dos autores para um HashMap com o "id" sendo o e-mail para já garantir que nenhum elemento duplicado fosse criado e além disso também adicionei uma verificação para garantir o mesmo. Além disso, criei um teste com JUnit para dentro da classe testes.

2020-06-04 18:55 UTC, yurioliveirazup requested changes
O @albertotavareszup vai dar uma olhadinha também 😄

2020-06-04 18:55 UTC, yurioliveirazup commented on src/br/com/zup/nossacasacodigo/author/Author.java
> +	public Author() {
_Idealmente, todo código escrito deveria ser chamado por alguém. Se não tem ninguém chamando, ele não deveria existir._

No projeto, este construtor não está sendo utilizado ainda, idealmente ele não precisaria existir. (Caso precisasse existir por alguma exigência de um framework, por exemplo, existem algumas formas que a gente pode deixá-lo sem influenciar muito em quem usa o código)

2020-06-04 18:55 UTC, yurioliveirazup commented on src/br/com/zup/nossacasacodigo/author/Author.java
> +	private String createdAt;
Qual a vantagem de utilizar uma string para representar a data e não um tipo específico? O que poderia acontecer se alguém passasse uma data em um formato inválido, ou então um texto qualquer?

2020-06-04 18:55 UTC, yurioliveirazup commented on src/br/com/zup/nossacasacodigo/author/Author.java
> +	public void setEmail(String email) {
Novamente aqui no caso dos setters, você ainda não está utilizando muito eles ainda na aplicação. [Esse post do Paulo da Caelum fala um pouco sobre isso](https://blog.caelum.com.br/nao-aprender-oo-getters-e-setters/). 

É muito comum a gente quando vai criar uma classe já ir pensando em fazer os getters e setters, mas é sempre importante ponderar se faz sentido criar o código naquele momento

2020-06-04 18:55 UTC, yurioliveirazup commented on src/br/com/zup/nossacasacodigo/author/Author.java
> +	public Author(String name, String email, String description, String createdAt) {
_Usamos o construtor para criar o objeto no estado válido._

O que acontece se, por um acaso, em algum outro ponto do código alguém chamar esse construtor e passar dados inválidos? Ou esquecer de chamar o validador antes? 

Como podemos sempre que chamarmos o construtor de `Author` ter um autor em um estado válido?

2020-06-04 18:55 UTC, yurioliveirazup commented on src/br/com/zup/nossacasacodigo/controllers/AuthorService.java
> +public class AuthorService {
_Toda indireção aumenta a dificuldade de entendimento da aplicação como um todo, ela precisa merecer existir. Ou seja, precisa ajudar a distribuir a carga intrínseca pelo sistema._

Essa classe está servido para trabalhar com a lista de autores que você está criando. É comum existirem classes de serviços que trabalham sobre os objetos. Mas nesse momento, será que faz sentido já criar essa classe, ou para manter a feature funcionando você pode só criar uma lista no momento dos testes?

2020-06-04 18:55 UTC, yurioliveirazup commented on src/br/com/zup/nossacasacodigo/controllers/AuthorService.java
> +		check.emailValidator(email);
O que aconteceria se alguém esquecesse de chamar esses validadores na hora de criar um autor? O que poderia ser feito para que o validador sempre fosse chamado quando um autor estivesse para ser criado?

2020-06-04 18:55 UTC, yurioliveirazup commented on src/br/com/zup/nossacasacodigo/controllers/Validator.java
> +public class Validator {
É legal que o nome da classe revele a intenção dela no projeto. `Validator` pode ser um nome muito genérico, pode ser que gere dúvidas, como o que essa classe valida de fato? Nesse ponto, acho que deixar o nome um pouco mais específico ajude

2020-06-04 18:55 UTC, yurioliveirazup commented on src/br/com/zup/nossacasacodigo/controllers/Validator.java
> +			String expression = "^[\\w\\.-]+@([\\w\\-]+\\.)+[A-Z]{2,4}$";
Expressões regulares podem ser muito complexas, como no caso dessa de email. Nesse caso, deixar um comentário para ajudar a falar o que essa expressão representa pode ajudar

2020-06-04 18:55 UTC, yurioliveirazup commented on src/br/com/zup/nossacasacodigo/controllers/Validator.java
> +			throw new RuntimeException("Email inv�lido");
Bem legal aqui você utilizar uma `Exception` quando uma entrada inválida é passada! O bacana das exceções é que elas podem ser mais semânticas de acordo com o tipo de erro. Por exemplo, o que acha de utilizar uma `IllegalArgumentException` nesse caso?

2020-06-04 18:55 UTC, yurioliveirazup commented on src/br/com/zup/nossacasacodigo/author/Author.java
> +	// nome, email e uma descri��o
_Deixamos pistas que facilitem o uso do código onde não conseguimos resolver com compilação._

Achei bem legal que você comenta o código!

Em geral, comentários podem ser utilizados para dar mais semântica, explicar o porquê de um trecho, ou serem utilizados como forma de documentação. [Aqui tem um texto bacana, mas em inglês, sobre comentários](https://refactoring.guru/smells/comments). 

O Alberto tem um vídeo legal sobre o assunto também: https://youtu.be/7g4aeMKwGcs

O que acha de revisitar os comentários do seu código e ver lugares assim que, talvez, possam ficar sem comentários?

2020-06-04 19:27 UTC, larissafabiao commented on src/br/com/zup/nossacasacodigo/author/Author.java
> +	public Author() {
Realmente, havia criado este construtor para utilizar em um dos testes sem o Junit mas agora que estou realizando os testes com ele não preciso mais.

2020-06-04 19:38 UTC, larissafabiao commented on src/br/com/zup/nossacasacodigo/author/Author.java
> +	private String createdAt;
Como nunca tinha usado uma função de tempo/data no java acabei pesquisando algumas e optei por utilizar a getDateTime(), que retorna uma String e por isso optei por representar a data como uma String. Mas pensando em inserir um formato inválido faria sentido porém isso seria possível sendo que somente o próprio sistema pega o horário e a data usando o getDateTime() ?

2020-06-04 19:57 UTC, larissafabiao commented on src/br/com/zup/nossacasacodigo/controllers/AuthorService.java
> +		check.emailValidator(email);
Poderia colocar o validador dentro do construtor?

2020-06-04 20:15 UTC, larissafabiao commented on src/br/com/zup/nossacasacodigo/author/Author.java
> +	public void setEmail(String email) {
Realmente, faz sentido. Nunca tinha pensado nesse assunto desta forma e faz muito sentido.

2020-06-04 22:01 UTC, larissafabiao commented on src/br/com/zup/nossacasacodigo/controllers/AuthorService.java
> +public class AuthorService {
Por questão de organização acabei preferindo deixar separado para centralizar meus controles dos Autores e permitir que esses métodos fiquem centralizados. Desta forma, consigo controlar o acesso ao Map e reaproveitar os métodos de busca e retorno dos Autores. Mas compreendo que poderiam estar também direto no teste.

2020-06-04 22:01 UTC, larissafabiao commented on src/br/com/zup/nossacasacodigo/controllers/Validator.java
> +			String expression = "^[\\w\\.-]+@([\\w\\-]+\\.)+[A-Z]{2,4}$";
Realmente, fiz alguns comentários para explicar a lógica que usei

2020-06-04 22:01 UTC, larissafabiao commented on src/br/com/zup/nossacasacodigo/controllers/Validator.java
> +			throw new RuntimeException("Email inv�lido");
Realmente faz sentido, não conhecia essa exception e faz sentido agora utiliza-la.

2020-06-05 14:24 UTC, yurioliveirazup requested changes

2020-06-05 14:24 UTC, yurioliveirazup commented on src/br/com/zup/nossacasacodigo/author/Author.java
> +		AuthorService service = new AuthorService();
Aqui você acha que é mais interessante receber o service, ou utilizar o validador direto?

2020-06-05 14:24 UTC, yurioliveirazup commented on src/br/com/zup/nossacasacodigo/controllers/AuthorsInformarionValidators.java
> +	public void emailValidator(String email, Map<String, Author> authors) {
Nesse caso, será que faz sentido esses métodos serem estáticos?

2020-06-05 14:24 UTC, yurioliveirazup commented on src/br/com/zup/nossacasacodigo/test/AuthorServiceTest.java
> +	public void test() {
O que acha de deixar o nome do teste mais semântico para explicar a funcionalidade?

2020-06-05 14:24 UTC, yurioliveirazup commented on src/br/com/zup/nossacasacodigo/test/AuthorServiceTest.java
> +public class AuthorServiceTest extends TestCase {
Acho que aqui faltou um teste com a lista de autores, né?

2020-06-05 14:24 UTC, yurioliveirazup commented on src/br/com/zup/nossacasacodigo/test/AuthorServiceTest.java
> +		//texto de exemplo com exatamente 400 caracteres
Excelente comentário 😄

2020-06-05 17:06 UTC, larissafabiao commented on src/br/com/zup/nossacasacodigo/author/Author.java
> +		AuthorService service = new AuthorService();
Acho que acaba sendo mais interessante utilizar o service por ele centralizar as informações em uma unica função e como já tenho que usar o Validator para outras funções do service, acabo centralizando essas chamadas

2020-06-05 17:07 UTC, larissafabiao commented on src/br/com/zup/nossacasacodigo/test/AuthorServiceTest.java
> +public class AuthorServiceTest extends TestCase {
Você diz com mais de um autor?

2020-06-05 19:38 UTC, yurioliveirazup approved these changes

2020-06-05 19:38 UTC, yurioliveirazup commented on src/br/com/zup/nossacasacodigo/controllers/AuthorsInformarionValidators.java
> +		if(isEmailValid == false) {
Só uma perguntinha, por que nesse caso não utilizar a negação, como`if (!isEmailValid) { ... }`?

2020-06-05 19:41 UTC, merged

2020-06-05 21:02 UTC, larissafabiao commented on src/br/com/zup/nossacasacodigo/controllers/AuthorsInformarionValidators.java
> +		if(isEmailValid == false) {
Nesse caso preferi por particularmente considerar mais claro mas também é uma boa opção

2020-06-05 22:26 UTC, albertotavareszup commented on src/br/com/zup/nossacasacodigo/author/Author.java
> +		AuthorsInformarionValidators.emailValidator(email);
*Toda indireção aumenta a dificuldade de entendimento da aplicação como um todo, ela precisa merecer existir. Ou seja, precisa ajudar a distribuir a carga intrínseca pelo sistema.*

Oi Larissa, perdão o meu atraso, mas acho que vale a pena aqui. Toda classe que criamos constitui uma indireção no sistema. Isso quer dizer que precisamos passar por ali para saber qual código está sendo executado. O seu validator entra nesse quesito. Pq vamos criar essa classe nova se podemos resolver sem criar?

2020-06-05 22:26 UTC, albertotavareszup commented on src/br/com/zup/nossacasacodigo/author/Author.java
> +	private Date createdAt;
Desde o Java 8 temos a classe LocalDateTime para trabalhar com data. Ela é a recomendada pela linguagem, além de possuir métodos mais interessantes do que o Date. Sugiro trocar.

2020-06-05 22:26 UTC, albertotavareszup commented on src/br/com/zup/nossacasacodigo/controllers/AuthorService.java
> +public class AuthorService {
Oi Larissa, é que fazer o revisão usando uma régua mais lógica justamente para evitar preferências :). A indireção aumenta a dificuldade do sistema e ela precisa merecer existir do ponto lógico. Se o mesmo código poderia ser feito sem, nossa sugestão é que fique sem :). 

PS: Provavelmente quando chegar a feature de verificar autor duplicado, talvez possamos pensar nela :). Por sinal, ainda não precisamos verificar autor duplicado :)

2020-06-05 22:26 UTC, albertotavareszup commented on src/br/com/zup/nossacasacodigo/controllers/AuthorsInformarionValidators.java
> +		if(isEmailValid == false) {
Aqui realmente não faz muita diferença. Dado que não faz diferença, é importante a gente dizer que você vai encontrar poucos códigos comparando com false ou true.