Exibir a Página de detalhe de um livro
larissafabiao/nossa-casa-codigo pull request #8
Opened 2020-06-24 17:07 UTC by larissafabiao

2020-06-24 19:49 UTC, yurioliveirazup requested changes

2020-06-24 19:49 UTC, yurioliveirazup commented on src/br/com/zup/nossacasacodigo/book/Book.java
> +	public void printBookInfo () {
As informações que tem que aparecer na tela são mais uma regra de visualização ou fazem parte do livro também?

2020-06-24 19:49 UTC, yurioliveirazup commented on src/br/com/zup/nossacasacodigo/database/Database.java
> +			if (name.compareToIgnoreCase(book.getTitle()) == 0) {
Por que não usar aqui um `equalsIgnoreCase` da String?

2020-06-24 19:49 UTC, yurioliveirazup commented on src/br/com/zup/nossacasacodigo/database/Database.java
> +	public Optional<Book> searchBook(String name) {
Com esse método, a classe `Database` ficou com 8 pontos de carga:

3 classes que você criou:
- Author (+ 1)
- Book (+ 1)
- Category (+ 1)

Um `if` nos métodos:

- checkIfIsUnic (+ 1)
- searchCategory (+ 1)
- searchAuthor (+ 1)

Um loop (+ 1) e um `if` (+ 1) no método de searchBook

8 ainda é um número ok (a gente tenta trabalhar com um limite de 9), mas o que a gente poderia fazer para diluir essa carga?

2020-06-24 19:49 UTC, yurioliveirazup commented on src/br/com/zup/nossacasacodigo/database/Database.java
> +	public Optional<Book> searchBook(String name) {
Um bom uso do `Optional` aqui 😄

2020-06-24 19:56 UTC, larissafabiao commented on src/br/com/zup/nossacasacodigo/book/Book.java
> +	public void printBookInfo () {
Acredito que fazem parte de uma regra de visualização porém optei por coloca-los no book pois assim evitaria de criar os getters para todos os parâmetros.

2020-06-24 19:58 UTC, larissafabiao commented on src/br/com/zup/nossacasacodigo/database/Database.java
> +			if (name.compareToIgnoreCase(book.getTitle()) == 0) {
Realmente, acaba tornando a expressão mais simples utilizar o equalsIgnoreCase

2020-06-24 20:00 UTC, larissafabiao commented on src/br/com/zup/nossacasacodigo/database/Database.java
> +	public Optional<Book> searchBook(String name) {
Para diminuir talvez seja a hora de separar esta classe em 3, atribuindo uma a cada estrutura de armazenamento. Outra coisa que estou pensando a algum tempo seria unir a chamada da inserção de um item no map porém ainda não consegui pensar em uma maneira de tornar este método genérico.

2020-06-25 09:30 UTC, albertotavareszup requested changes

2020-06-25 09:30 UTC, albertotavareszup commented on src/br/com/zup/nossacasacodigo/book/Book.java
> +	private Object categoryValidator(Object obj) {
Oi Larissa! Aqui talvez seja reflexo da nossa generalização dentro da classe do banco de dados(apenas um chute, me perdoe se eu estiver equivocado). Se você realmente quer fazer um verificador de nulo genérico, object é o canal. Só que como você fazer para tirar a necessidade do cast?

2020-06-25 09:30 UTC, albertotavareszup commented on src/br/com/zup/nossacasacodigo/auxiliars/ShowABook.java
> +			book.printBookInfo();
Esse daqui é um ótimo ponto de reflexão, vi que @yurioliveirazup começou a falar sobre o assunto em outro comentário também e que vocês já começaram a debater. Não existe problema em ter y ou x métodos se eles realmente são necessários :). 

Por exemplo, neste caso aqui: como que seu método printBookInfo sabe a formatação do valor? Como ele sabe que precisa printar "Conteudo:" antes do conteúdo em si?  

Muitas vezes, quando precisamos escrever o código que chama e também o código que implementa, criamos um acoplamento mental que nem sentimos. Se o preço para não estar acoplado for alto, provavelmente vale a pena começar. Só que neste caso ficar acoplado ou não aumenta(ou aumenta pouco) o nível de dificuldade do entendimento do código(dada a régua que estamos trabalhando). 

@yurioliveirazup, não sei se já explicou, mas acho que chegou o momento de explicar para Larissa e Maurício a nossa métrica de dificuldade de entendimento :).

2020-06-25 09:30 UTC, albertotavareszup commented on src/br/com/zup/nossacasacodigo/database/Database.java
> +	public Optional<Book> searchBook(String name) {
tinha até falado da métrica lá em cima, massa que já estão utilizando.

2020-06-25 09:30 UTC, albertotavareszup commented on src/br/com/zup/nossacasacodigo/database/Database.java
> +	public Optional<Book> searchBook(String name) {
Sobre dividir em 3 Larissa, tenta fazer a divisão pelo olhar da métrica. Será que precisa mesmo de 3 para diluir?

2020-06-25 17:11 UTC, larissafabiao commented on src/br/com/zup/nossacasacodigo/book/Book.java
> +	private Object categoryValidator(Object obj) {
Oi Alberto ! Na verdade acabei optando por criar esse validador genérico pois na classe de Livros precisamos ter uma categoria e um autor não nulos. Logo, para evitar criar dois códigos que fariam a mesma coisa (receber um objeto e verificar se é nulo ou não e retorna-lo) pensei em criar o método genérico que inclusive acabei de perceber que o nome precisa ser alterado. Para tirar a necessidade do cast a primeira solução que penso seria talvez eliminar o retorno do objeto e transforma-lo em uma função void. Existiria alguma outra opção?

2020-06-25 17:18 UTC, larissafabiao commented on src/br/com/zup/nossacasacodigo/database/Database.java
> +	public Optional<Book> searchBook(String name) {
Olhando melhor o código pensei em talvez reorganizar de forma a mandar verificações como a checkIfIsUnic para uma classe do pacote de classes auxiliares, o que ajudaria a diminuir a carga da classe. Outra opção que pensei seria separar somente a classe de Books pois este possui um comportamento mais complexo, inclusive uma busca diferenciada.

2020-06-25 17:21 UTC, larissafabiao commented on src/br/com/zup/nossacasacodigo/book/Book.java
> +	private Object categoryValidator(Object obj) {
Porém, qual seria a vantagem de deixar de usar o cast? Diminuir a probabilidade de erro em execução?

2020-06-26 09:46 UTC, albertotavareszup commented on src/br/com/zup/nossacasacodigo/book/Book.java
> +	private Object categoryValidator(Object obj) {
O cast traz incerteza, exato. E se temos a chance de tirar a incerteza a um custo razoável, parece válido :). 

Da para resolver assim:

```
public <T> T nullVerifier(T object){
   if(object == null){
      //lanca exception
   }
   return object;
}
```

Aqui a gente usou o recurso dos generics :). A mesma ideia é utilizada na implementação das coleções do java por exemplo.

2020-06-26 09:51 UTC, albertotavareszup requested changes

2020-06-26 09:51 UTC, albertotavareszup commented on src/br/com/zup/nossacasacodigo/auxiliars/ShowABook.java
> +			bookToPrint.getBookDetail().printBookInfo();
Oi Larissa, o que eu quis dizer da outra vez é que os System.out.println poderiam ficar aqui direto :). Pq estou falando isso? Pq você de lá de dentro não sabe o formato de saída dos dados... Claro que podemos considerar que a classe BookDetails pode ser utilizada apenas para impressão, mas nesse caso não temos necessidade dela. Ela não divide nenhuma responsabilidade pelo olhar do nível de entendimento que estamos trabalhando.

2020-06-26 13:52 UTC, yurioliveirazup commented on src/br/com/zup/nossacasacodigo/auxiliars/ShowABook.java
> +			bookToPrint.getBookDetail().printBookInfo();
O comentário do Alberto faz sentido. Nesse ponto eu pensava em usar a `BookDetails` como um DTO para a impressão...

2020-06-26 16:32 UTC, larissafabiao commented on src/br/com/zup/nossacasacodigo/book/Book.java
> +	private Object categoryValidator(Object obj) {
Nossa, realmente ! Havia esquecido dessa implementação de generics, faz sentido a ideia!

2020-06-26 16:39 UTC, larissafabiao commented on src/br/com/zup/nossacasacodigo/auxiliars/ShowABook.java
> +			bookToPrint.getBookDetail().printBookInfo();
Entendi Alberto, faz sentido ! Então nesse caso a criação dos getters acaba sendo justificada e não prejudicial por possibilitar essa flexibilização do código?

2020-06-29 15:22 UTC, yurioliveirazup approved these changes
Bem legal o código! Se o @albertotavareszup não tiver comentário, acho que tudo bem seguir para a próxima tarefa

2020-06-29 15:22 UTC, yurioliveirazup commented on src/br/com/zup/nossacasacodigo/auxiliars/ShowABook.java
> +			System.out.println("R$ " + book.getPrice());
Só a título de curiosidade, se você quiser, aqui você pode utilizar uma classe de formatação, como a `NumberFormat` ou a `DecimalFormat`.

Esse [post mostra um pouco como utilizar essas classes](https://receitasdecodigo.com.br/java/numberformat-ou-decimalformat-formatar-numeros-reais-em-java)

2020-07-01 09:07 UTC, albertotavareszup approved these changes
Eu não poderia ser mais lento, me perdoem!

2020-07-01 11:54 UTC, merged