Itens no carrinho de compra
larissafabiao/nossa-casa-codigo pull request #9
Opened 2020-06-29 18:03 UTC by larissafabiao

2020-06-29 22:07 UTC, yurioliveirazup requested changes

2020-06-29 22:07 UTC, yurioliveirazup commented on src/br/com/zup/nossacasacodigo/database/IsbnName.java
> +public class IsbnName implements Comparable {
Onde você está utilizando essa classe?

2020-06-29 22:07 UTC, yurioliveirazup commented on src/br/com/zup/nossacasacodigo/database/CollectionsValidatorsAndGetters.java
> +public class CollectionsValidatorsAndGetters {
Acho que aqui só ficou como `Validators` agora né? haha

2020-06-29 22:07 UTC, yurioliveirazup commented on src/br/com/zup/nossacasacodigo/database/Database.java
> +	public <T> T searchAuthorOrCategory(String key, Map<String, T> database) {
Aqui para fazer a busca a pessoa que chama esse método precisa passar a coleção que a busca vai ser feita... e se ela não tiver essa coleção em mãos, ou passar uma coleção errada? Como podemos prevenir isso de acontecer?

2020-06-29 22:09 UTC, larissafabiao commented on src/br/com/zup/nossacasacodigo/database/IsbnName.java
> +public class IsbnName implements Comparable {
Era para uma das implementações que tinha pensado para solucionar a unicidade do ISBN e do nome nos livros. Porém, como não deu certo acabei excluindo ela, estranho o git não ter mostrado.

2020-06-29 22:09 UTC, larissafabiao commented on src/br/com/zup/nossacasacodigo/database/CollectionsValidatorsAndGetters.java
> +public class CollectionsValidatorsAndGetters {
verdade kk

2020-06-29 22:18 UTC, larissafabiao commented on src/br/com/zup/nossacasacodigo/database/Database.java
> +	public <T> T searchAuthorOrCategory(String key, Map<String, T> database) {
Pensei em passar a coleção como parâmetro pois sempre que é inserido um novo elemento, retornamos o Map ao qual ele foi inserido. Porém, para não depender deste talvez seria possível usar uma função lambda ou então, utilizando um método menos eficaz, talvez usar um identificador para cada map e realizar um if na hora de fazer as buscar ou talvez, menos eficaz ainda, buscar nas três em uma estrutura de if com uma das buscas retornando um resultado válido senão estourando uma exceção.

2020-07-02 15:06 UTC, yurioliveirazup requested changes

2020-07-02 15:06 UTC, yurioliveirazup commented on src/br/com/zup/nossacasacodigo/cart/Cart.java
> +	public  void addToCart(String wanted, Database db) {
Qual a vantagem de receber o título do livro e o database aqui para fazer a busca? Se esse método já recebesse o livro que é preciso ser adicionado, o que simplificaria no código?

A gente pode pensar também no fluxo do site. A pessoa já buscou o livro e, depois de buscar, ver os detalhes, adiciona o livro no carrinho. Nesse momento a gente já tem o livro que a pessoa buscou, só precisamos adicionar ele no carrinho. Faz sentido?

2020-07-02 15:06 UTC, yurioliveirazup commented on src/br/com/zup/nossacasacodigo/cart/Cart.java
> +	private List<Book> cart = new ArrayList<Book>();
Os nomes dos atributos estão muito relacionados sobre como o negócio chama esses dados. Um carrinho tem um carrinho como atributo? Será que outro nome, como `items` ou `books` chega mais próximo do conceito de negócio?

2020-07-02 16:06 UTC, larissafabiao commented on src/br/com/zup/nossacasacodigo/cart/Cart.java
> +	public  void addToCart(String wanted, Database db) {
Faz sentido Yuri, não havia pensado nessa possibilidade e nem no fato de já termos o livro. Isso retira a necessidade de fazer uma nova busca.

2020-07-02 16:07 UTC, larissafabiao commented on src/br/com/zup/nossacasacodigo/cart/Cart.java
> +	private List<Book> cart = new ArrayList<Book>();
Realmente, inicialmente pensei em nomear como cart por ser realmente o carrinho mas isso acaba gerando uma redundância com relação aos nomes

2020-07-02 21:14 UTC, yurioliveirazup commented on src/br/com/zup/nossacasacodigo/database/DatabaseTest.java
> +	@BeforeEach
Apanhamos um pouquinho do Junit haha

2020-07-02 21:27 UTC, yurioliveirazup approved these changes
Se o @albertotavareszup não tiver comentários, por mim está ok 😄

2020-07-02 21:27 UTC, yurioliveirazup commented on src/br/com/zup/nossacasacodigo/cart/showCart.java
> +public class showCart {
Para seguir o padrão do Java, vamos deixar essa classe começando com a letra maiúscula também?

2020-07-02 21:27 UTC, yurioliveirazup commented on src/br/com/zup/nossacasacodigo/cart/Cart.java
> +	private static BigDecimal finalValue = new BigDecimal("0.0");
Por curiosidade, existe uma constante da classe `BigDecimal` com o valor 0 <https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/math/BigDecimal.html#ZERO>

2020-07-02 21:37 UTC, larissafabiao commented on src/br/com/zup/nossacasacodigo/cart/showCart.java
> +public class showCart {
Opa, claro !!

2020-07-02 21:41 UTC, larissafabiao commented on src/br/com/zup/nossacasacodigo/cart/Cart.java
> +	private static BigDecimal finalValue = new BigDecimal("0.0");
Interessante, não tinha visto. Muda algo significante usar a string ou o Zero do próprio BigDecimal?

2020-07-02 21:53 UTC, yurioliveirazup commented on src/br/com/zup/nossacasacodigo/cart/Cart.java
> +	private static BigDecimal finalValue = new BigDecimal("0.0");
Basicamente assim `new BigDecimal("0.0");` a gente tem uma nova inicialização no sistema. Mas eles são, sintaticamente, iguais

2020-07-03 19:06 UTC, merged